; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc-- < %s | FileCheck %s --check-prefixes=CHECK,PPC32
; RUN: llc -mtriple=powerpcle-w64-windows-gnu < %s | FileCheck %s --check-prefixes=CHECK,PPC32
; RUN: llc -mtriple=powerpc64-- < %s | FileCheck %s --check-prefixes=CHECK,PPC64

define i128 @udiv_i128(i128 %x, i128 %y) nounwind {
; CHECK-LABEL: udiv_i128:
; PPC32-NOT: bl __
; PPC64:    bl __udivti3
  %res = udiv i128 %x, %y
  ret i128 %res
}

define i129 @udiv_i129(i129 %x, i129 %y) nounwind {
; CHECK-LABEL: udiv_i129:
; CHECK-NOT: bl __
  %res = udiv i129 %x, %y
  ret i129 %res
}
